POST http://localhost:1234/api/login
Content-Type: application/json

{
    "login": "doctor",
    "password": "doctor"
}

###

GET http://localhost:1234/api/doctors/658712e411893f7cb9895a64

###

GET http://localhost:1234/api/patients/658705e53b786ef1006e04fb

###

GET http://localhost:1234/api/patients

###

GET http://localhost:1234/api/admin/65880207e075c93418fd6619